extends:
  - eslint:recommended
  - airbnb
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - standard-with-typescript
  - standard-react
ignorePatterns:
  - /next.config.js
  - /next-env.d.ts
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    excludedFiles: pages/**/*
    rules:
      import/no-default-export: error
parserOptions:
  project: ./tsconfig.json
plugins:
  - no-autofix
  - react-hooks
root: true
rules:
  arrow-body-style: off
  comma-dangle: [error, always-multiline]
  curly: [error, all]
  jsx-quotes: [error, prefer-single]
  max-classes-per-file: off
  multiline-ternary: [error, never]
  newline-per-chained-call: off # bug?
  no-mixed-operators:
    - error
    - groups:
        - ["&", "|", "^", "~", "<<", ">>", ">>>"]
        - ["==", "!=", "===", "!==", ">", ">=", "<", "<=", "in", "instanceof"]
  no-nested-ternary: off
  no-param-reassign:
    - error
    - props: false
  no-plusplus: off # bugs will be fixed soon
    #- error
    #- allowForLoopAfterthoughts: true
  no-restricted-syntax: off
  no-var: error
  prefer-const: off # -> no-autofix/prefer-const
  semi-style: [error, first]
  sort-imports:
    - error
    - ignoreDeclarationSort: true # -> import/order
  yoda:
    - error
    - never
    - onlyEquality: true

  import/extensions:
    - error
    - ts: never
      tsx: never
  import/no-default-export: off
  import/order:
    - error
    - alphabetize:
        order: asc
  import/prefer-default-export: off

  jsx-a11y/anchor-is-valid:
    - error
    - components: [Link]
      specialLink: [hrefLeft, hrefRight]
      aspects: [invalidHref, preferButton]
  jsx-a11y/label-has-associated-control:
    - error
    - assert: either
      controlComponents: ['NumberInput', 'ValidatingInput']

  no-autofix/prefer-const:
    - error
    - destructuring: all

  react/jsx-closing-tag-location: off
  react/jsx-filename-extension: off
  react/jsx-props-no-spreading: off
  react/prop-types: off
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error

  '@typescript-eslint/keyword-spacing':
    - error
    - overrides:
        if: { after: false }
        for: { after: false }
        while: { after: false }
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/space-before-function-paren':
    - error
    - anonymous: never
      asyncArrow: always
      named: never
  '@typescript-eslint/strict-boolean-expressions': off
settings:
  import/resolver:
    node:
      extensions: [.js, .jsx, .ts, .tsx]
  react:
    version: detect
